# Generated by Django 2.1.5 on 2019-08-02 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict_entry', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predict',
            old_name='internetservice',
            new_name='internet_service',
        ),
    ]
