# Generated by Django 2.1.5 on 2019-08-06 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict_entry', '0002_auto_20190802_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='predict',
            name='multiple_lines',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('No phone service', 'No phone service')], default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='predict',
            name='online_backup',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('No internet service', 'No internet service')], default=1, max_length=30),
        ),
        migrations.AddField(
            model_name='predict',
            name='online_security',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('No internet service', 'No internet service')], default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='predict',
            name='phone_service',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='predict',
            name='stream_mov',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('No internet service', 'No internet service')], default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='predict',
            name='stream_tv',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('No internet service', 'No internet service')], default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='predict',
            name='tech_support',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='predict',
            name='tenure',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='predict',
            name='contract',
            field=models.CharField(choices=[('One year', 'One year'), ('Month-to-month', 'Month-to-month'), ('Two year', 'Two year')], default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='predict',
            name='internet_service',
            field=models.CharField(choices=[('DSL', 'DSL'), ('Fiber optic', 'Fiber optic'), ('No', 'No')], default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='predict',
            name='payment',
            field=models.CharField(choices=[('Bank transfer (automatic)', 'Bank transfer (automatic)'), ('Credit card (automatic)', 'Credit card (automatic)'), ('Electronic check', 'Electronic check'), ('Mailed check', 'Mailed check')], default=1, max_length=50),
        ),
    ]
